# Generated by Django 3.0.8 on 2020-10-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=30)),
                ('ItemID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('Tname', models.CharField(max_length=30)),
                ('TID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TerritoryItemMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse_Stock', models.IntegerField(blank=True, null=True)),
                ('Store_Stock', models.IntegerField(blank=True, null=True)),
                ('Transit_Stock', models.IntegerField(blank=True, null=True)),
                ('Price', models.DecimalField(decimal_places=10, max_digits=14)),
                ('ItemID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Item')),
                ('TerritoryID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Territory')),
            ],
        ),
    ]
