# Generated by Django 3.0.8 on 2020-10-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ItemID',
            new_name='Item',
        ),
    ]
